sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product testn-055
env:
  global:
    -
      # LTD_AWS_ID
      secure: prX6CwQ3HF14p/uEUEu2TBnwB3VyT/ouEfRD37SjoOiHx8V3xZlMW72qTe7Ctg8NZIXWNeE4A+p/k/AGzTyB/PIjBkui31c8yt2T1AvAQ1aF4ISaWP99JUtc44csGoKWMp67DAk0+VVKH7k15M26QkMaL2sv0sqm6Co2eBuPn55PPHUqk8IQTPP84MWR+uGVmkpYP790XgUCaI+yandoM04sMGzUhwMbEiU0SCwcv8ZZmATfwna2wXJxAqRkRENUunaPzHeKhRGbksn7+HMnKCSNHAKJmfqDIHSdIIkfrl+T7S8csdSZJbEz7L2cxgsoVKyILDfwJBji0PHxGinrYPRWI8yE1PMmhT1Iwct0DtCJT2Zs/72sZg+4yw0MUIWEimM49swfaN3FG5zfKM8zyKLA00XKcLJhDSJzMWg75psRrpUQPkRUl0pxxZpK25NWzzG2dX/og7rE/Pn4pno5Y4LOAj3WLT9Ov7AXGl9RDPvqSaS96pA+T8lIwixsUGW0Vq+jZPgKxDloxfzgJN8hAVOElqD5xOzKfu6ejbKph8rpulyjc5/C8GUH6swwlnxXi+vw7f5nEuu3F8jWdnd/QtvQ2ZnbpKvQmWumBsK8TxEWWz2o5Q8PJu9TGZvHX9CYUNzFoVDvTJCkifqXza5wnXly1hoLoqOb3Z9NF31W0mw=
    -
      # LTD_AWS_SECRET
      secure: PfaQHIPbKqNwXgFpL/+6CLp5lhnZ9Z6Q2+75WWkpAJ/jYUwBtOuo/uYcTF0j/6C0T44YdFk7/0um3if44aZnj7oD1vRxJP77aEaY662udv02sA0YI384QR8CQTBf9i2aZgm18pVnZ90PHNkIcOg9JOmqKJrsC+BaYcAOsheBFBK7YbL13G1yZT99w7cxoqpADPGOB6LwnSKBBEHJWfemUuLvq7v6GuOpgIUrVPqQpLVEXF2RJtdYv8NjhdQ7Y3Z+NsdJUlg3AxaOvSjdFJVuVq+ivWMGNjhMZJJAk8TWyi/M6iTL5245icsf3X+5nv2Iwi+o72awqSxjI+NK3JU3j5TZzFR4WWiIQJ/qA3wVresWeTx2d8+khhOPWZbIuN1iwb8fCOC+kAroIrZ5PrAQTFXrpltjmYj8PkpeVf7iM6YhbRHsySOrp9VwUix7UtejjIBpyxa1RKjdd4X4WmNa9FsNXnfUd49izRRkOEqNUnHvGu6Juis+o8PYCYFoqxotw3wCKg04w7n39/35VggV8j129/PiHk3Ze0x12ZEyEAHo3+ShehMoSw4QUIq4u7VZDVVZtw9zbWRr0UkHDu7bzr8KMLGHbXOrdpmi1Hjs81LgwCDbSzZQW6nXAtdmEj+R1qYnBxf1nevhQkNrgA2m46u9D85qUgWMIuZMrEZGrs0=
    -
      # LTD_USERNAME
      secure: AqqVer+O1HMeETep5kwOQgjpMIuKNWLsGkLDVX02LHh/F1X1oYw7qLNaIAIl0cZt1WRXS3t+f3ZyS0zXH0tfo5R6CSJiup/BZ+K0SIaTU2Bjlnk5l5Qd93hyZ516dHMxDrDLpyhopy1WOVbP9Uo+YQgDm6Wz4KpLAIclJ1OZAXSYCXnHy4WPTPtrrpo9Xpk34SPzUGOyBU5Ie6f+OvfkAAti5GPlMI4k21wmx6L81YZSH7xezco1jBCwvZ1ZQzBvz9vomjPL3sz+aGWi5GLJ5z/A4YPiHS5uniz8k+3yar6S7MfZi3XaM4bfrmcrrtioo01vtZwAXu749oRz8D46lENYqp8L/orA6iYrPpU8Ky1jGdo2YmdUvQlCOsp9SG/1ZUASJpDmS3469Euzn4/3rRf/50dxtlQfs4s7YRHJS6eTPTczcBw5NkrpdFKTtdjIc0i2CjeiUzN+CnBJWW7l+XdPeneQfICt6mIYdPNhb4f5VGCMEzKTM2J++GE85uemHR2hhVmaLyt7o4oX5nS7263CWM8jIh0rO6u+zZFRYxxVjwzMfT2Xradt4UuPCsRHKApoApVtOXDHax5Mop+8MB9FpJARtErmy2fEzVTLhfpnb+VZipNw1eQMb7FWQ7roXV5/zoJ1CIs9fc8SoCnKxdyyjd+E2J7t3fSEYIS1CHk=
    -
      # LTD_PASSWORD
      secure: sHLEBaI7n+5PqLaKmtmfrc08lafgXvPT+LBPCnUEsye+PRI5Nainz/cqFO1qL6HlZCPvKsfbMhUicjAw2m4XsljuW4BfyaSQt2uGjXrQvGzGcFviy73X+Qrj15k6mKoxWyB0yrSJZGgdQun7mIIxaNKGsTk+FHfhfYC9DQA1CGrPJD6fyEk0Myps6ciTh/BjptXM+zsk0ZMWaTfxkIuLt6dYKohiu/28nHMafTjopARsEhOz36mmq/EQ/vFlH5BYWULGYFrCVBitU89w0H44N4Hx32IcttxxYH+cQJ4shDX1K0x8Wl0qO7ypKpZCAfbZ0e1H4xbmIrLlRGukJjGdjvc5h5i2FaIgMG2g6Dp1Pz2d/WJrOsG3+Sl+lSgzBVHVWM8W8SN9+K/G7MB7WP/U6xxuFo/TM3TX+201qpIFw2tp1kTgoyQCX8ekEG+T+Z84IiDN75QL8aMndnI1XavBrj+GTnrkKrTHDIKGAnps1R7Cn0tZM5qw8oRqJSr34vj9STMkVkeaTNuAXxP2PyaD9bdQMFU59CVC9SehvjNTBEIol46AFE2YVF1gehTs/vm182/51GkEyAkjPwxnVNey17jmqjmm4e0yklWpXPI8HmlkMtjTdkA9qjdLB5yVl4PQeR1D1TExhi9TZ2QHahnaxCBil1cb4saKYYgB4dqEZ5U=
